# Generated by Django 2.2.4 on 2019-10-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_python'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='python',
            name='category',
        ),
        migrations.RemoveField(
            model_name='python',
            name='name',
        ),
    ]
