# Generated by Django 2.2.4 on 2019-10-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191020_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('video', models.FileField(default='', upload_to='videos/python')),
            ],
        ),
        migrations.CreateModel(
            name='Css',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('video', models.FileField(default='', upload_to='videos/python')),
            ],
        ),
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('video', models.FileField(default='', upload_to='videos/python')),
            ],
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('video', models.FileField(default='', upload_to='videos/python')),
            ],
        ),
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('video', models.FileField(default='', upload_to='videos/python')),
            ],
        ),
        migrations.CreateModel(
            name='Javascript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('video', models.FileField(default='', upload_to='videos/python')),
            ],
        ),
    ]
