# Generated by Django 2.2.4 on 2019-10-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_c_css_django_html_java_javascript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='video',
            field=models.FileField(default='', upload_to='videos/C'),
        ),
        migrations.AlterField(
            model_name='css',
            name='video',
            field=models.FileField(default='', upload_to='videos/css'),
        ),
        migrations.AlterField(
            model_name='django',
            name='video',
            field=models.FileField(default='', upload_to='videos/django'),
        ),
        migrations.AlterField(
            model_name='html',
            name='video',
            field=models.FileField(default='', upload_to='videos/Html'),
        ),
        migrations.AlterField(
            model_name='java',
            name='video',
            field=models.FileField(default='', upload_to='videos/java'),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='video',
            field=models.FileField(default='', upload_to='videos/javascript'),
        ),
    ]
